version = "v1"
brand   = "rc-http-sim"
model   = "http"

[tcp]
    ip = "127.0.0.1"
    port = 502
          
    [tcp.http]

        [[tcp.http.channel]]
            channel_id  = "BT"
            label       = "bean temp"
            unit        = "celcius"
            color       = "#00007f"
            ror_color   = "#dd0000" # BT only

        [[tcp.http.channel]]
            channel_id  = "ET"
            label       = "exhaust temp"
            unit        = "celcius"
            color       = "#ff0000"
            
        [[tcp.http.channel]]
            channel_id  = "inlet"
            label       = "inlet temp"
            unit        = "celcius"
            color       = "#007f00"

[manual]

    [[manual.range_input]]
        min         = 0
        max         = 100
        step        = 10        # 0 means no steps
        default     = 20

        [manual.range_input.channel]
            channel_id  = "gas"
            label       = "GAS"
            unit        = "mmHg"
            color       = "#007f00"

    [[manual.range_input]]
        min         = 0
        max         = 50
        step        = 5         # 0 means no steps
        default     = 30

        [manual.range_input.channel]
            channel_id  = "fan"
            label       = "FAN"
            unit        = "Pa"
            color       = "#007f00"
