version = "v1"
brand   = "rc-http-sim"
model   = "http"

[tcp]
    ip = "127.0.0.1"
    port = 502
          
    [tcp.http]

        [[tcp.http.channel]]
            channel_id  = "BT"
            label       = "bean temp"
            unit        = "celcius"
            color       = "#00007f"
            ror_color   = "#dd0000" # BT only

        [[tcp.http.channel]]
            channel_id  = "ET"
            label       = "exhaust temp"
            unit        = "celcius"
            color       = "#ff0000"
            
        [[tcp.http.channel]]
            channel_id  = "inlet"
            label       = "inlet temp"
            unit        = "celcius"
            color       = "#007f00"
            
