version = "v1"
brand   = "rc-http-sim"
model   = "http"

# pnpm tauri dev -- -- --config=../machines/kapok/501_inlet_rtu.toml

[tcp]
    ip = "127.0.0.1"
    port = 502
          
    [tcp.http]

        [[tcp.http.channel]]
            channel_id  = "BT"
            label       = "bean temp"
            unit        = "celcius"
            color       = "#191970"
            ror_color   = "#4169E1" # BT only

        [[tcp.http.channel]]
            channel_id  = "ET"
            label       = "exhaust temp"
            unit        = "celcius"
            color       = "#ff0000"
            
        [[tcp.http.channel]]
            channel_id  = "inlet"
            label       = "inlet temp"
            unit        = "celcius"
            color       = "#2E8B57"

[[manual_channel]]
    channel_id  = "gas"
    label       = "Gas"
    unit        = "mmHg"
    color       = "#007f00"
    min         = 0
    max         = 100
    step        = 10        # 0 means no steps
    default_value     = 20

[[manual_channel]]
    channel_id  = "airflow"
    label       = "Airflow"
    unit        = "Pa"
    color       = "#007f00"
    min         = 20
    max         = 50
    step        = 5         # 0 means no steps
    default_value     = 30

[[alarm]]
    id              = 1
    src_channel_id  = "BT"
    from            = "TP"    # CHARGE, TP, DRY_END, FC_START, FC_END, SC_START, SC_END, DROP
    condition       = "above" # above, below
    value           = 170
    [alarm.speech_synthesis]
        utterance   = "170"

[[alarm]]
    id              = 1
    src_channel_id  = "BT"
    from            = "TP"    # CHARGE, TP, DRY_END, FC_START, FC_END, SC_START, SC_END, DROP
    condition       = "above" # above, below
    value           = 180
    [alarm.speech_synthesis]
        utterance   = "180"
