version = "v1"
brand   = "roastcraft"
model   = "modbus"
# metrics_ids = [
#     "exhaust_temp",
#     "bean_temp",
#     "inlet_temp",
#     "air",
# ]

# [serial]
#     port      = "COM4"
#     baud_rate = 9600
#     data_bits = 8
#     parity    = "none"
#     stop_bits = 1

#     [serial.modbus]
#         # modbus-ascii, modbus-rtu
#         protocol = "modbus-ascii"

#         [[serial.modbus.slave]]
#             metrics_id = "exhaust_temp"
#             id         = 1
#             function   = 3
#             registry   = 18176
#             multiplier = 0.1

#         [[serial.modbus.slave]]
#             metrics_id = "bean_temp"
#             id         = 2
#             function   = 3
#             registry   = 18176
#             multiplier = 0.1

#         [[serial.modbus.slave]]
#             metrics_id = "inlet_temp"
#             id         = 3
#             function   = 3
#             registry   = 18176
#             multiplier = 0.1

# [tcp]
#     ip   = "127.0.0.1"
#     port = 502

#     [tcp.modbus]
#         protocol = "modbus-tcp"

#         [[tcp.modbus.slave]]
#             metrics_id = "air"
#             id         = 4
#             function   = 3
#             registry   = 18176
#             multiplier = 0.1
