version = "v1"
brand = "tasi"
model = "ta612c"
metrics_ids = [
    "bean_temp",
    "exhaust_temp",
]

[serial]
    port      = "COM4"
    baud_rate = 9600
    data_bits = 8
    parity    = "none"
    stop_bits = 1
