version = "v1"
brand   = "roastcraft"
model   = "modbus"

[serial]
    port      = "COM4"
    baud_rate = 9600
    data_bits = 8
    parity    = "none"
    stop_bits = 1

    # [[serial.ta612c]]
    #     metrics_id = "BT"
    #     id         = 1

    # [[serial.ta612c]]
    #     metrics_id = "ET"
    #     id         = 2

    [[serial.modbus]]
        protocol    = "rtu" # rtu, ascii, tcp
        metrics_id  = "ET"
        id          = 1
        function    = 3
        registry    = 18176
        divisor     = 10    # 1, 10, 100
        number_type = "u16" # u16, u32, i16, i32, f32

    [[serial.modbus]]
        protocol    = "rtu" # rtu, ascii, tcp
        metrics_id  = "BT"
        id          = 2
        function    = 3
        registry    = 18176
        divisor     = 10    # 1, 10, 100
        number_type = "u16" # u16, u32, i16, i32, f32

    [[serial.modbus]]
        protocol    = "rtu"   # rtu, ascii, tcp
        metrics_id  = "inlet"
        id          = 3
        function    = 3
        registry    = 18176
        divisor     = 10      # 1, 10, 100
        number_type = "u16"   # u16, u32, i16, i32, f32

[tcp]
    ip   = "127.0.0.1"
    port = 502

    [[tcp.modbus]]
        protocol    = "tcp"     # rtu, ascii, tcp
        metrics_id  = "em2000h"
        id          = 4
        function    = 3
        registry    = 20
        divisor     = 1         # 1, 10, 100
        number_type = "f32"     # u16, u32, i16, i32, f32
