version = "v1"
brand = "roastcraft"
model = "modbus"


[serial]
    port      = "COM4"
    baud_rate = 9600
    data_bits = 8
    parity    = "none"
    stop_bits = 1

    [serial.modbus]
        # modbus-ascii, modbus-rtu
        protocol = "modbus-ascii"

        [[serial.modbus.slave]]
            channel_id = "exhaust_temp"
            id         = 1
            function   = 3
            registry   = 18176
            multiplier = 0.1

        [[serial.modbus.slave]]
            channel_id = "bean_temp"
            id         = 2
            function   = 3
            registry   = 18176
            multiplier = 0.1

        [[serial.modbus.slave]]
            channel_id = "inlet_temp"
            id         = 3
            function   = 3
            registry   = 18176
            multiplier = 0.1

[tcp]
    ip   = "127.0.0.1"
    port = 502

    [tcp.modbus]
        protocol = "modbus-tcp"

        [[tcp.modbus.slave]]
            channel_id = "air"
            id         = 4
            function   = 3
            registry   = 18176
            multiplier = 0.1
